### ISSUE TITLE
CT: PhET-iO API error about registration of dynamic instances

### ISSUE THREAD

**Issue by jbphet** [phetsims/quantum-measurement#38]
@AgustinVallejo and I enabled phet-io for this sim yesterday, and there is now a phet-io-related CT error that we should address.  Here is an excerpt:

```
quantum-measurement : phet-io-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1727199033439/quantum-measurement/quantum-measurement_en.html?continuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1727199033439%22%2C%22timestamp%22%3A1727199543554%7D&ea&brand=phet-io&phetioStandalone&fuzz
ERROR: QUERY: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed: PhET-iO API error:
quantumMeasurement.coinsScreen.view.classicalCoinsExperimentSceneView.measurementArea.multiCoin0:  1. After startup, only dynamic instances prescribed by the baseline file can be registered.
STACK: Error: Assertion failed: PhET-iO API error:
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1727199033439/assert/js/assert.js:45:13)
    at assert (phetioAPIValidation.ts:273:18)
    at assertAPIError (phetioAPIValidation.ts:183:15)
    at listener (Timer.ts:33:10)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Sim.ts:1038:24)
```

**Comment by jbphet** [comment]
This was caused, at least in part, by the dynamic creation of the nodes used to animate the movement of coins from the preparation area to the multi-coin measurement area.  I changed the code so that these nodes are all created during load time for the sim, and things seem to be working better.  I'll keep an eye on CT and see if it clears up.

**Comment by jbphet** [comment]
CT is green, closing.
