### ISSUE TITLE
CT Uncaught Error: Assertion failed: required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quantum-measurement#51]
```
quantum-measurement : phet-io-active-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728473978957%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:112:4)
    at  (RectangularRadioButton.ts:110:24)
    at  (RectangularRadioButtonGroup.ts:222:26)
    at  (SpinScreenView.ts:58:42)
    at  (SpinScreen.ts:34:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:919:15)
    at  (Sim.ts:927:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1728471600625%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728473978957%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1728471600625%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728473978957%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728473978957%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/quantum-measurement/quantum-measurement_en.html?brand=phet-io&ea&postMessageOnError&sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728473978957%7D
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.04100486424055538,
  "currentScreenName": "HomeScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new RectangularRadioButton (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:76:25)
    at new RectangularRadioButtonGroup (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButtonGroup.js:145:27)
    at new SpinScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/view/SpinScreenView.js:49:43)
    at SpinScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/SpinScreen.js:24:18)
    at SpinScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:772:21
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new RectangularRadioButton (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:76:25)
    at new RectangularRadioButtonGroup (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButtonGroup.js:145:27)
    at new SpinScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/view/SpinScreenView.js:49:43)
    at SpinScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/SpinScreen.js:24:18)
    at SpinScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:772:21
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 10/9/2024, 5:00:00 AM

----------------------------------

quantum-measurement : phet-io-active-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728481124019%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:112:4)
    at  (RectangularRadioButton.ts:110:24)
    at  (RectangularRadioButtonGroup.ts:222:26)
    at  (SpinScreenView.ts:58:42)
    at  (SpinScreen.ts:34:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:919:15)
    at  (Sim.ts:927:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1728471600625%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728481124019%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1728471600625%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728481124019%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728481124019%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/quantum-measurement/quantum-measurement_en.html?brand=phet-io&ea&postMessageOnError&sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728481124019%7D
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.5924830986267386,
  "currentScreenName": "HomeScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new RectangularRadioButton (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:76:25)
    at new RectangularRadioButtonGroup (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButtonGroup.js:145:27)
    at new SpinScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/view/SpinScreenView.js:49:43)
    at SpinScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/SpinScreen.js:24:18)
    at SpinScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:772:21
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new RectangularRadioButton (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:76:25)
    at new RectangularRadioButtonGroup (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButtonGroup.js:145:27)
    at new SpinScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/view/SpinScreenView.js:49:43)
    at SpinScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/SpinScreen.js:24:18)
    at SpinScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:772:21
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 10/9/2024, 5:00:00 AM

----------------------------------

quantum-measurement : phet-io-data-stream-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/phet-io-wrappers/data-stream/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728471963223%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:112:4)
    at  (RectangularRadioButton.ts:110:24)
    at  (RectangularRadioButtonGroup.ts:222:26)
    at  (SpinScreenView.ts:58:42)
    at  (SpinScreen.ts:34:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:919:15)
    at  (Sim.ts:927:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1728471600625%2Fphet-io-wrappers%2Fdata-stream%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728471963223%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1728471600625%2Fphet-io-wrappers%2Fdata-stream%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728471963223%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/phet-io-wrappers/data-stream/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728471963223%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/quantum-measurement/quantum-measurement_en.html?brand=phet-io&ea&postMessageOnError&sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1728471600625%22%2C%22timestamp%22%3A1728471963223%7D&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.4019338547173186,
  "currentScreenName": "HomeScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new RectangularRadioButton (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:76:25)
    at new RectangularRadioButtonGroup (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButtonGroup.js:145:27)
    at new SpinScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/view/SpinScreenView.js:49:43)
    at SpinScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/SpinScreen.js:24:18)
    at SpinScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:772:21
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new RectangularRadioButton (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:76:25)
    at new RectangularRadioButtonGroup (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/sun/js/buttons/RectangularRadioButtonGroup.js:145:27)
    at new SpinScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/view/SpinScreenView.js:49:43)
    at SpinScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/quantum-measurement/js/spin/SpinScreen.js:24:18)
    at SpinScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1728471600625/chipper/dist/js/joist/js/Sim.js:772:21
[CONSOLE] continuous-test-wrapper-error

id: "Bayes Node Puppeteer"
Snapshot from 10/9/2024, 5:00:00 AM
```

**Comment by jbphet** [comment]
@AgustinVallejo - I think this is due to missing `tandemName` options in some of the radio buttons in the spin controls.
