### ISSUE TITLE
CT Assertion failed: required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quantum-measurement#56]
```
quantum-measurement : phet-io-active-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729072397313%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:112:4)
    at  (StickyToggleButtonModel.ts:51:4)
    at  (RoundStickyToggleButton.ts:51:30)
    at  (LaserPointerNode.ts:191:20)
    at  (PhotonEmitterNode.ts:28:29)
    at  (PhotonTestingArea.ts:37:30)
    at  (PhotonsExperimentSceneView.ts:32:30)
    at  (PhotonsScreenView.ts:36:44)
    at  (PhotonsScreen.ts:34:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:919:15)
    at  (Sim.ts:927:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1729071929044%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729072397313%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1729071929044%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729072397313%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729072397313%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/quantum-measurement/quantum-measurement_en.html?brand=phet-io&ea&postMessageOnError&sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729072397313%7D
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.17132839760880403,
  "currentScreenName": "HomeScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new StickyToggleButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/StickyToggleButtonModel.js:32:5)
    at new RoundStickyToggleButton (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/RoundStickyToggleButton.js:35:31)
    at new LaserPointerNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/scenery-phet/js/LaserPointerNode.js:119:55)
    at new PhotonEmitterNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonEmitterNode.js:17:30)
    at new PhotonTestingArea (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonTestingArea.js:26:31)
    at new PhotonsExperimentSceneView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsExperimentSceneView.js:19:31)
    at new PhotonsScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsScreenView.js:22:45)
    at PhotonsScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/PhotonsScreen.js:24:18)
    at PhotonsScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:772:21
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new StickyToggleButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/StickyToggleButtonModel.js:32:5)
    at new RoundStickyToggleButton (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/RoundStickyToggleButton.js:35:31)
    at new LaserPointerNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/scenery-phet/js/LaserPointerNode.js:119:55)
    at new PhotonEmitterNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonEmitterNode.js:17:30)
    at new PhotonTestingArea (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonTestingArea.js:26:31)
    at new PhotonsExperimentSceneView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsExperimentSceneView.js:19:31)
    at new PhotonsScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsScreenView.js:22:45)
    at PhotonsScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/PhotonsScreen.js:24:18)
    at PhotonsScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:772:21
[CONSOLE] continuous-test-wrapper-error

id: "Bayes Node Puppeteer"
Snapshot from 10/16/2024, 3:45:29 AM

----------------------------------

quantum-measurement : phet-io-active-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729076207351%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:112:4)
    at  (StickyToggleButtonModel.ts:51:4)
    at  (RoundStickyToggleButton.ts:51:30)
    at  (LaserPointerNode.ts:191:20)
    at  (PhotonEmitterNode.ts:28:29)
    at  (PhotonTestingArea.ts:37:30)
    at  (PhotonsExperimentSceneView.ts:32:30)
    at  (PhotonsScreenView.ts:36:44)
    at  (PhotonsScreen.ts:34:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:919:15)
    at  (Sim.ts:927:25)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1729071929044%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729076207351%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1729071929044%2Fphet-io-wrappers%2Factive%2F%3Fsim%3Dquantum-measurement%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=15000&testInfo=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729076207351%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/phet-io-wrappers/active/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729076207351%7D
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/quantum-measurement/quantum-measurement_en.html?brand=phet-io&ea&postMessageOnError&sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729076207351%7D
[CONSOLE] enabling assert
[CONSOLE] Assertion failed:  required tandems must be supplied
[CONSOLE] Debug info: {
  "seed": 0.099518932784745,
  "currentScreenName": "HomeScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new StickyToggleButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/StickyToggleButtonModel.js:32:5)
    at new RoundStickyToggleButton (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/RoundStickyToggleButton.js:35:31)
    at new LaserPointerNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/scenery-phet/js/LaserPointerNode.js:119:55)
    at new PhotonEmitterNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonEmitterNode.js:17:30)
    at new PhotonTestingArea (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonTestingArea.js:26:31)
    at new PhotonsExperimentSceneView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsExperimentSceneView.js:19:31)
    at new PhotonsScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsScreenView.js:22:45)
    at PhotonsScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/PhotonsScreen.js:24:18)
    at PhotonsScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:772:21
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at EnabledProperty.initializePhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:151:7)
    at new PhetioObject (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/tandem/js/PhetioObject.js:133:12)
    at new ReadOnlyProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/ReadOnlyProperty.js:110:5)
    at new Property (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/Property.js:12:5)
    at new BooleanProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/BooleanProperty.js:24:5)
    at new EnabledProperty (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledProperty.js:33:5)
    at new EnabledComponent (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/axon/js/EnabledComponent.js:37:55)
    at new ButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/ButtonModel.js:70:5)
    at new StickyToggleButtonModel (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/StickyToggleButtonModel.js:32:5)
    at new RoundStickyToggleButton (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/sun/js/buttons/RoundStickyToggleButton.js:35:31)
    at new LaserPointerNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/scenery-phet/js/LaserPointerNode.js:119:55)
    at new PhotonEmitterNode (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonEmitterNode.js:17:30)
    at new PhotonTestingArea (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonTestingArea.js:26:31)
    at new PhotonsExperimentSceneView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsExperimentSceneView.js:19:31)
    at new PhotonsScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/view/PhotonsScreenView.js:22:45)
    at PhotonsScreen.createView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/quantum-measurement/js/photons/PhotonsScreen.js:24:18)
    at PhotonsScreen.initializeView (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Screen.js:233:23)
    at Array.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:763:16)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/chipper/dist/js/joist/js/Sim.js:772:21
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 10/16/2024, 3:45:29 AM

----------------------------------

quantum-measurement : phet-io-data-stream-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/phet-io-wrappers/data-stream/?sim=quantum-measurement&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22quantum-measurement%22%2C%22phet-io-data-stream-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1729071929044%22%2C%22timestamp%22%3A1729072907862%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1729071929044/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (ReadOnlyProperty.ts:176:4)
    at  (Property.ts:17:4)
    at  (BooleanProperty.ts:31:4)
    at  (EnabledProperty.ts:45:4)
    at  (EnabledComponent.ts:68:54)
    at  (ButtonModel.ts:112:4)
    at  (StickyToggleButtonModel.ts:51:4)
    at  (RoundStickyToggleButton.ts:51:30)
    at  (LaserPointerNode.ts:191:20)
    at  (PhotonEmitterNode.ts:28:29)
    at  (PhotonTestingArea.ts:37:30)
    at  (PhotonsExperimentSceneView.ts:32:30)
    at  (PhotonsScreenView.ts:36:44)
    at  (PhotonsScreen.ts:34:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim.ts:919:15)
    at  (Sim.ts:927:25)
====================
```

**Comment by jbphet** [comment]
I committed a fix and checked CT after an hour or so, and it's now green.  Closing.
